language: R
cache:
  - packages
  - directories:
    - /tmp/texlive
    - $HOME/.texlive
sudo: required
warnings_are_errors: false

r:
  - release
  - devel

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-base
  - tlmgr install pgfplots algorithmicx
r_build_args: '--no-build-vignettes'
r_check_args: '--ignore-vignettes --no-examples'

after_success:
  - Rscript -e 'pkgdown::build_site()'
  
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master