language: R
cache:
  - packages
  - directories:
    - /tmp/texlive
    - $HOME/.texlive
sudo: required
warnings_are_errors: false
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install texlive-latex-base
  - tlmgr install pgfplots algorithmicx